### PR TITLE
openshift: rename runtimclass from kata-oc to kata

### PR DESCRIPTION
**Pull request by jensfr**
Many users asked to rename the runtime class name because kata-oc is unexpected.
There's no technical reason not to change it, so let's do it. 

Signed-off-by: Jens Freimann <jfreimann@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@jensfr, grepping for kata-oc I see more files that could be changed:
```
fidencio@dahmer ~/src/upstream/kata-operator $ git grep kata-oc
README.md:Once the kata runtime binaries are successfully installed on the intended workers, Kata Operator will create a [runtime class](https://kubernetes.io/docs/concepts/containers/runtime-class/) `kata-oc`. This runtime class can be used to deploy the pods that will use the Kata Runtime.
README.md:3. To check if the nodes in the machine config pool are going through a config update watch the machine config pool resource. For this do `watch oc get mcp kata-oc`
deploy/example-fedora.yaml:  runtimeClassName: kata-oc
pkg/controller/kataconfig/openshift_reconciler.go:              Values:   []string{"kata-oc", "worker"},
pkg/controller/kataconfig/openshift_reconciler.go:                      Name: "kata-oc",
pkg/controller/kataconfig/openshift_reconciler.go:              workerRole = "kata-oc"
pkg/controller/kataconfig/openshift_reconciler.go:      c := RuntimeConfig{RuntimeName: "kata-oc"}
pkg/controller/kataconfig/openshift_reconciler.go:      runtimeClassName := "kata-oc"
pkg/controller/kataconfig/openshift_reconciler_test.go: err = k.client.Get(context.TODO(), types.NamespacedName{Name: "kata-oc"}, mcp)
pkg/controller/kataconfig/openshift_reconciler_test.go: err = k.client.Get(context.TODO(), types.NamespacedName{Name: "kata-oc"}, rc)
pkg/controller/kataconfig/openshift_reconciler_test.go: err = k.client.Get(context.TODO(), types.NamespacedName{Name: "kata-oc"}, mcp)
pkg/controller/kataconfig/openshift_reconciler_test.go: err = k.client.Get(context.TODO(), types.NamespacedName{Name: "kata-oc"}, rc)
```

So, README and example-fedora also have to be changed.

**Comment by jensfr** [comment]
you're right, I removed it from the README and also changed example-fedora.yaml. Deleted example-fedora-k8s.yaml as they only difference was the runtime class name. Thanks for the review!

**Comment by fidencio** [comment]
> you're right, I removed it from the README and also changed example-fedora.yaml. Deleted example-fedora-k8s.yaml as they only difference was the runtime class name. Thanks for the review!

As you deleted the example-fedora-k8s.yaml, you need to update this bit here[0] as it still points to the removed file.
[0]: https://github.com/openshift/kata-operator#run-an-example-pod-using-the-kata-runtime-1

Last bit, you have a typo in the commit log: s/runtimclass/runtimeclass/ (there's an 'e' missing there).

**Review by harche — APPROVED** [review]

**Review by fidencio — APPROVED** [review]

**Pull request merged**
